"""
Optional LLM narrative for validator results — grounded in deterministic validationPayload.

Slim OpenAI/Bedrock path (same pattern as analyst_narrative). Never changes tickerValidation.
"""

from __future__ import annotations

import json
import logging
import os
import re
from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict, Field

from alphalens_shared.services.validator_report import (
    attach_validation_notes,
    build_deterministic_validation_report,
    build_validation_executive_summary,
    validate_validation_narrative,
)

logger = logging.getLogger(__name__)

AGENT_NAME = "Validator Narrator"

VALIDATOR_NARRATIVE_INSTRUCTIONS = """
You are the AlphaLens ticker validation narrator. Validation status is ALREADY
computed by deterministic rules and yfinance — you must NOT change tickerValidation values.

Your job: explain the validation results clearly for an investor.

Rules:
- Use ONLY facts in validationPayload (ticker, tickerValidation, validationReason, companyName)
- Do not invent tickers, prices, or exchange listings
- Do not upgrade unknown/invalid tickers to validated
- Every candidateNotes entry must use a ticker from validationPayload
- methodologyNote must state validation came from code/yfinance, not from you
- executiveSummary is generated by the system from counts — focus on candidateNotes
- When describing counts, use "no" for zero (never "0"), e.g. "no unknown tickers"
- Respond with ONLY valid JSON (no markdown fences)
"""

OUTPUT_HINT = """
JSON shape:
{
  "executiveSummary": "...",
  "candidateNotes": [{"ticker": "TSM", "summary": "..."}],
  "methodologyNote": "..."
}
"""


class TickerNote(BaseModel):
    model_config = ConfigDict(extra="forbid")

    ticker: str
    summary: str


class ValidationReportOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    executiveSummary: str
    candidateNotes: List[TickerNote] = Field(default_factory=list)
    methodologyNote: str


def narrative_enabled() -> bool:
    return os.getenv("USE_LLM_VALIDATOR_NARRATIVE", "false").lower() == "true"


def create_narrative_task(validation_payload: Dict[str, Any]) -> str:
    payload_json = json.dumps(validation_payload, indent=2)[:14000]
    return f"""
Explain these discovery candidate validation results for the user.

Deterministic validation payload (source of truth — do not contradict statuses):
{payload_json}

{OUTPUT_HINT}
""".strip()


def _extract_json(text: str) -> Dict[str, Any]:
    raw = text.strip()
    fence = re.search(r"```(?:json)?\s*(\{.*\})\s*```", raw, re.DOTALL)
    if fence:
        raw = fence.group(1)
    start = raw.find("{")
    end = raw.rfind("}")
    if start >= 0 and end > start:
        raw = raw[start : end + 1]
    return json.loads(raw)


def run_narrative_slim(_payload: Dict[str, Any], result: Dict[str, Any]) -> Dict[str, Any]:
    from alphalens_shared.bedrock_agent import get_llm_provider

    validation_payload = result.get("validationPayload") or {
        "candidates": result.get("validatedCandidates", []),
    }
    task = create_narrative_task(validation_payload)
    provider = get_llm_provider()

    if provider == "openai":
        from openai import OpenAI

        api_key = os.getenv("OPENAI_API_KEY", "").strip()
        if not api_key:
            raise ValueError("OPENAI_API_KEY is required when LLM_PROVIDER=openai")
        model = os.getenv("OPENAI_MODEL_ID", "gpt-4.1-mini")
        client = OpenAI(api_key=api_key)
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": VALIDATOR_NARRATIVE_INSTRUCTIONS},
                {"role": "user", "content": task},
            ],
            response_format={"type": "json_object"},
            temperature=0.2,
        )
        content = response.choices[0].message.content or "{}"
    else:
        import boto3

        region = os.getenv("BEDROCK_REGION", "us-west-2")
        model_id = os.getenv("BEDROCK_MODEL_ID", "us.amazon.nova-pro-v1:0")
        client = boto3.client("bedrock-runtime", region_name=region)
        response = client.converse(
            modelId=model_id,
            system=[{"text": VALIDATOR_NARRATIVE_INSTRUCTIONS}],
            messages=[{"role": "user", "content": [{"text": task}]}],
            inferenceConfig={"maxTokens": 2048, "temperature": 0.2},
        )
        parts = response.get("output", {}).get("message", {}).get("content", [])
        content = next((p.get("text", "") for p in parts if "text" in p), "{}")

    parsed = ValidationReportOutput.model_validate(_extract_json(content))
    return _finalize(parsed.model_dump(), result)


def _finalize(report: Dict[str, Any], result: Dict[str, Any]) -> Dict[str, Any]:
    candidates = result.get("validatedCandidates") or []
    sanitized, guardrail_warnings = validate_validation_narrative(report, candidates)
    sanitized["executiveSummary"] = build_validation_executive_summary(candidates)
    if guardrail_warnings:
        logger.warning("Validator narrative guardrails: %s", "; ".join(guardrail_warnings))
        result.setdefault("warnings", []).extend(guardrail_warnings)
    if not sanitized.get("candidateNotes") and candidates:
        return build_deterministic_validation_report(result)
    return sanitized


def maybe_enrich_validator_narrative(
    payload: Dict[str, Any],
    result: Dict[str, Any],
) -> Dict[str, Any]:
    """Attach LLM validation narrative when USE_LLM_VALIDATOR_NARRATIVE=true."""
    if not narrative_enabled():
        return result
    if not result.get("success", True):
        return result

    try:
        report = run_narrative_slim(payload, result)
        attach_validation_notes(result, report)
        return result
    except ImportError:
        logger.warning("Validator LLM deps missing")
    except Exception:
        logger.exception("Validator LLM narrative failed — keeping deterministic report")

    result.setdefault("warnings", []).append(
        "LLM validation narrative unavailable; using deterministic validation report."
    )
    return result
